### ISSUE TITLE
Discussion about Observable .... 

### ISSUE THREAD

**Issue by kaifox** [ossgang/ossgang-commons#1]
Hi guys, 

as Michis initial commit is not a pull request, I am creating this issue about the 'Observable' Concept. I could do a pull request, but probably it is better to discuss first a bit ...

I personally see very strong parallels to the ossgang-properties ... So I cannot see this thing decoupled from the properties ... I rather would see this as a base for the properties...

1) I think I like the name 'Observable'
2) Concerning the Updateable, I have the question what is the difference to a 'Set' of a property... To me it looks rather the same?
3) I think Updateable should be an interface. Probably then one even would not need the abstract class, but this would be a concrete implementation implementing both interfaces.
4) If I think of properties, I would see that your abstract observable even implements the 3rd trait of a property the 'get', which is the value() method in the abstract class...

Concerning the implementation of the abstract class, I have the following remarks:
5) As I see, the subscriber always gets a first update. I think this deserves to be well documented, as I would not have it expected (this introduces an additional state in the observable). However, I even would think that this might be optional (either by a flag or potentially even a different implementation, as the value() method would not be possible then ....)). ... In the end, your `Updatable` is already a 'Property'.
6) The print stacktrace in the consumer, I do not really like ... I rather would tend to in the default implementation throw a runtime exception (I know this is not too cool ;-). (And I know it comes from the 'zero deps' ;-)
7) As an alternative (or extension) to (6) one could offer a way to attach a `Consumer<Throwable>` to this, so that the user could decide what to do .... Could e.g. be done in a builder-like (method chaining) syntax... or (in parallel to the subscribe) somehow like:
```
void subscribeOnError(Consumer<Throwable> listener);
void unsubscribeOnError(Consumer<Throwable> listener);
```
...

... Putting all my thought together (and the ones I had about the properties project, but never wrote down...) I would see:

Three interfaces:
```
public interface Setable<T> {
  void set(T value);
} 

public interface Getable<T> {
  T get();
}

public interface Observable<T> {
  void subscribe(Consumer<? super T> listener);
  void unsubscribe(Consumer<? super T> listener);
}
```

A property would then be ...
```
public interface Property<T> extends Setable<T>, Getable<T>, Observable<T> {
}
```
...

In this context one then could have a kind of simple observable that does not cache the last value and kind off a Cache1Observable that always publishes the first value on subscription...(Or constructor flags). 

I know this is bit of a long issue ... still, I hope I was not too confusing .... ;-)

**Comment by michi42** [comment]
Hi,

Thanks a lot for the comment. Maybe I should first explain a bit the design goal of this class(es) ... the idea ist to provide a very lightweight alternative to reactive streams using a simple observer/listener pattern which can be used in existing or refactored projects without adding a lot of dependencies - we were a bit reluctant to put Fluxes everywhere, also because final fate of japc-flux is still unclear (it might disappear eventually).

The idea of Observable<T> is NOT to be a generic dispatcher for events of type T, but to wrap a value of type T which can be observed for changes. Think of it more as an AtomicReference<T> with the extra feature of being observable, not as a stream with a state ;-)
This is why the basic interface has both methods to obtain the current value and to observe the value for future changes.

For Updateable, this is supposed to be the equivalent of the various publishing processors for reactive streams. Unlike a property with a Set method, it is not supposed to be exposed.
For instance, you would have an interface like
```java
public interface LsaDelegate {
    Observable<Optic> activeOptic();
}
```
and the implementation would be something like
```java
public class ProLsaDelegate implements LsaDelegate {
    private final Updateable<Optic> activeOptic;
    public ProLsaDelegate() {
        activeOptic = Updateable.withInitialValue(getActiveOptic());
        // code to subscribe to LSA active optic and call activeOptic.update(...) on change
    }
    public Observable<Optic> activeOptic() {
        return activeOptic;
    }
}
```
Indeed probably the same could be done with properties if we would split off get/subscribe and set ... And yes, thinking of that, Updateable is indeed already "kind of" a property if you want. Even though it was never meant to be that ;-)


For the "first update" - this was just for convenience for the application where this code came from, and I agree this is a behavior that could be re-discussed, even though for a slightly different reason: by definition of an Observable, it is easy to obtain the current value(), while there is no guarantee when exactly the first update will be sent (it is sent from another thread...), so implementations should probably anyway not rely on the first-update but rather get the value when they need it.
So for me, I would be fine with removing this (possibly adding an extra default method in the interface that implements this behaviour, like subscribeWithFirstUpdate() - or even a static method in some helper class).


For the print stack trace - I agree it's not nice, it used to be a logger but I changed it to get rid of slf4j as a dependency (by the way, I think AWT does the same if an exception happens in it's event dispatching thread? remember the infamous 'Exception in thread "AWT-EventQueue-0"' ...).
The problem is we can not throw there, as the dispatching happens in a cached thread pool executor, and letting an exception escape there would (by default) just kill one of the worker threads, and then probably the exception would get swallowed (unless an unhandled exception handler is defined).
Providing a way to get out the exceptions by providing a consumer/exception handler would be an option, but I would in any case provide a default behaviour that makes sure that exceptions are not swallowed if no custom exception handler is provided (it is just too easy to miss that, in particular if you have to register it for every updateable).

**Comment by michi42** [comment]
Another point that might be worth discussing: Weak or Strong references for listeners? I see clear advantages for both:

- Strong references avoid situations where a listener is "silently" garbage collected because it is only loosely coupled to another class and no reference exist (the classic JAPC anonymous class listener thingy).

- Weak references would possibly simplify the interface (would we need an explicit unsubscribe in that case?), and it would make things simpler if we ever plan to introduce derived observables (e.g. Observable.map(...)). Also, it would avoid memory leaks in cases where "disposed" classes are still referenced in a listener (I think I had this once with lumiserver tasks and their subscriptions ...)

Any preference for one way or the other?

**Comment by andreacalia** [comment]
Hi guys, I created a few other issues so this does not get messy :)

**Comment by andreacalia** [comment]
Thank you very much both for your comments! I think this concept can be nicely abstracted and will be useful for quite some applications..

My interpretation of the `Observable` is simply an implementation of the Observable/Observer pattern (hence the name). This means no state (or first update), just dispatching the value that a "producer" wants to deliver. This can be achieved in different ways, but 1 interface (subscribe method) + 1 implementation (with the notify/publish method) would suffice.
This would solve the general case of delivering updates.

I tend to agree that Properties and the current implementation of `Updatable` are very similar. If we want to keep `Updatable` I see the `Property` to extend `Updatable` in oss-properties-core.
I'm not so sure about the fact that `Updatable` extends `Observable`.. since the first update could lead to misunderstandings I would compose/delegate rather than extending.. it is easier to refactor composition than hierarchies :smile:. I would have to think about it though.. but I don't think we need it for the moment.. or do you rely on this Michi?

**Comment by michi42** [comment]
For the first update, I agree that having it unconditional may be confusing. I think it can be a useful behavior in some cases, sparing a few lines of boilerplate every once in a while, but it could be made explicit. For instance, if we go for the Subscription object as you proposed (#3), what about a requestFirstUpdate (or just requestUpdate?) on that object? So you could do something like
```observable.subscribe(this::myHandler).requestFirstUpdate()```

Anyway, it looks like we have a bit a different understanding of what an "Observable" or "Updateable" is ;-)
I always thought of it as a "wrapper" around a T with the "extra feature" of being observable for changes (something that is only subscribable but not gettable is more like an "event" than a "value"?)
But probably that name is too generic then.
What about a JavaFx like hierarchy:
Observable (subscribe) -> ObservableValue (subscribe,get) -> Property (subscribe,get,set)?
(which would go well along with Kajetans proposed traits of Getable/Setable)
Of course if we go for Andreas proposal in #3, this would mean that Observable subscribe() should return a basic Subscription object (without requestUpdate() as it can not do it), but ObservableValue subscribe() would return e.g. an UpdateableSubscription which can do requestUpdate().

I think the hierarchy should be maintained as long as it's not leading to too many issues, or then we should somehow come up with another solution for the (quite common) use case outlined above: you have some producer of values, e.g. an LSA delegate, which should be observable and readable (ObservableValue<T> in the proposal above) but NOT setable.
In the producer code itself, internally you want to use an object on which you can call a method to feed in an update (e.g. Property<T>, which you set() in a JAPC listener).
To prevent casting, one could even introduce an explicit read only wrapper.

**Comment by kaifox** [comment]
Ok , I think now I understand better your reasoning.... I think a hierarchy close to the javafx one is anyway good (as long as it reflects the purpose well), as it does not require users to learn new concepts...
The returned subscription object sounds to me like a good idea... 
There are then a few aspects which still remain, where I would tend to make them configurable with a reasonable default value:

* listener references: Could we make them strong references by default, but offer also a weak reference version? 
* error handling: default as michi proposes (to stderror). Potentially (or later) a way to subscribe to the errors.
* Dispatching/Scheduling: Default can well be the cached threadpool as in your examples. Howeveer, it could be useful to allow dispatching on e.g. single threads... (for testing or for javafx).... So probably one could introduce a scheduler concept, like in reactor...

I think all those things we do not have to implement right away, but start out with the defaults...

**Comment by andreacalia** [comment]
I like the hierarchy `Observable (subscribe) -> ObservableValue (subscribe,get) -> Property (subscribe,get,set)`.

This is then very clear what it does each step of it. I would not know how to implement the first update request on the Subscription (it could have already received something..) but we could provide different methods in the ObservableValue/Observable like: `.subscribe` and `.subscribeWithFirstUpdate`.

(btw I think the first update concept is very CERN specific.. we should document it)

I would personally use single threads for dispatching of events, but this could be configurable anyway :) Probably we could use common fork join pool that is used also by `CompletableFuture` :)

**Comment by michi42** [comment]
Yes, to do a reliable FIRST update on the subscription object is difficult - and yes, the concept is CERN specific. But it could just be called
``requestUpdate()``, by which request that the current value should be dispatched to the observer associated with the subscription object at the next occasion (a bit like "invalidate" or "repaint" in a GUI...).
In principle you could call that method also at any later stage, not just on subscription, which could potentially be useful in some edge case (I remember one in lumi server).

**Comment by kaifox** [comment]
Can we close this for the time being? All the important aspects pulled out in new items?

**Comment by michi42** [comment]
I guess so.
