### ISSUE TITLE
UpstreamConnectible

### ISSUE THREAD

**Issue by kaifox** [ossgang/ossgang-commons#24]
I have the impression that sometimes it is desirable to connect/disconnect from upstream subscriptions (e.g. closing japc subscriptions and reopen them.

My first proposal is new dedicated interface that can be implemented by observables and which allows this behaviour. I will soon submit a PR with a first proposal.

**Comment by kaifox** [comment]
here is the PR #25

**Comment by michi42** [comment]
Maybe I'm missing the point, but what exactly would be use cases for this? I'm just wondering because the connect/disconnect would intrinsically affect all subscribers, plus it may have side effects upstream ... is this really a desirable behavior?
Shouldn't we rather have a filter that can inhibit or forward updates? (a bit like switch observable, but switching on/off rather than switching source)

**Comment by kaifox** [comment]
I think the two approaches are complementary. Indeed this mechanism effects of course everything downstream and also has side effects upstream. I agree in a standard app, where you usually have all your streams running it is not required.
However, what I am trying to do at the moment is a more testing-application which has to subscribe (many) fesa subscriptions ... and they can produce quite substantial network load ... so I would like to have a way to really pause the fesa subscriptions to unload the servers and the network ... So there I need somehow the upstream side effect ... Any other ideas welcome ...

**Comment by michi42** [comment]
Ok, thanks a lot for the explanation, I see, yes, saving network load could be a valid use case.

On the other hand, what about having "disposable" subscriptions in this case? Just don't hold a strong reference to them, unsubscribe when you are done with them, and eventually they will get GC'd (and therefore stopped)?

I'm just a bit worried introducing a state that can be changed from the outside and affects all downstream subscribers (who might not be aware of this, as they just get an observable) and has upstream side effects (which will eventually be seen downstream, e.g. by getting a new JAPC first update on re-subscribe). I'm afraid this could be very difficult to debug, in particular if the signal to connect/disconnect does not come directly from the user but from some other source.

**Comment by kaifox** [comment]
Yes I agree that such things could be tricky to debug ....

With disposable subscriptions: How would I turn them back on? I would have to recreate ... so I would have to have a producer instead of the observable value and rebind them in the start of the stream ...  looks to me like quite some more effort ...... however, the downstream effects would be similar (except the japc first update)... 

Probably, one should still document the danger ...
I think nothing of this I would do in a GUI which does simple tasks ... but, just to mention:Here we are really talking about  bunch by bunch data etc and I do not really want to kkep all subscriptions open ... 
And isnt the switchable filter also a state which can be changed from outside (and also the buffer), which effects all downstream ...

... Lets wait for Andreas comments (I just do not have any much better idea)

**Comment by michi42** [comment]
True, the transformations like filter or buffer (if they are mutable) are also states ... I just didn't think of them as something you would share between many subscribers, whereas e.g. JapcObservable is something at the very root of the tree and therefore (potentially) shared a lot if e.g. returned by a service.

Another thing I could think of, as a maybe a bit more generic option ... what about a ConntectorObservable which would have something like this:
```
ConnectorObservableValue<T> extends ObservableValue<T> {
    void connect(ObservableValue<T> upstream);
    void disconnect();
}
```
if connected, it would forward updates (and get()) from/to upstream to all subscribers. If disconnected, it would discard any reference to upstream, allowing them to be GC'd. So in your case you could put these in front of your JapcObservable, disconnect() once you want to stop exceptions, and re-create JapcObservables and connect() them once you need them back.

Obviously, this also effects all downstream subscribers (with your use case in mind it is difficult to do otherwise), but it would in my opinion separate responsibilities more clearly.
In general, I'm more in favor of building chains of simple transformations/operations than having "fat" observables which do everything internally ;-)

**Comment by andreacalia** [comment]
Hi guys!

I think we need this feature, so it's very good to start looking into this! :smile: 
I think that the chain based approach suggested by Michi with the `ConnectorObservableValue` could be the more flexible in the long term. With the `UpstreamConnectible` the producer will have more fine grained control over its own behaviour, but will require that every Observable that support this functionality to implement the interface.
If we make it another step in the chain of observable we possibly allow the user to "break" the chain at any point to introduce joints that can be changed at runtime. This could be a powerful option in the future (e.g. hot switching Observables).

There could be two versions of `ConnectorObservableValue`, one that always connects to an Observable produced by a `Supplier<Observable>` and another one that can be connected to any Observable that matches the T. The first case would be useful for Kajetan's usecase, the other for the switching in wonderland/demo mode :smile: 

Extending Michi's proposal, maybe something like this? (name to be decided..)
```java
DynamicConnectorObservableValue<T> extends ObservableValue<T> {
    void connect(ObservableValue<T> upstream);
    void disconnect();
}

ConnectorObservableValue<T> extends ObservableValue<T> {
    void connect();
    void disconnect();
}
```

**Comment by kaifox** [comment]
Dear both thanks for your comments.

I think, what is in the proposal is more-or-less the second option that Andrea proposes, except that not those 2 methods are exposed, but another property which allows this switching. This makes the connection state observable.

I think the first variant one could also call Pluggable or similar.

In any case, I agree that we have to be careful to not introducing too many differnt concepts ;-)

If Andreas first example would belong to a property, then I would say, one would just bind it to the upstream (property). But indeed, for Observable (or ObservableValue) this concept does not exist, or?

**Comment by andreacalia** [comment]
Hi @kaifox , let's continue on the #25 :relaxed:
